"""feynman_session

Revision ID: 033233505aa3
Revises: e4ad1e7b8012
Create Date: 2026-04-27 14:14:09.299371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '033233505aa3'
down_revision: Union[str, Sequence[str], None] = 'e4ad1e7b8012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create feynman_kind enum idempotently before table creation
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE feynman_kind AS ENUM ('fresh', 'scheduled');
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feynman_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=True),
    sa.Column('target_concept_id', sa.Uuid(), nullable=False),
    sa.Column('kind', postgresql.ENUM('fresh', 'scheduled', name='feynman_kind', create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feynman_session_paper_id'), 'feynman_session', ['paper_id'], unique=False)
    op.create_index(op.f('ix_feynman_session_target_concept_id'), 'feynman_session', ['target_concept_id'], unique=False)
    op.create_index(op.f('ix_feynman_session_user_id'), 'feynman_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feynman_session_user_id'), table_name='feynman_session')
    op.drop_index(op.f('ix_feynman_session_target_concept_id'), table_name='feynman_session')
    op.drop_index(op.f('ix_feynman_session_paper_id'), table_name='feynman_session')
    op.drop_table('feynman_session')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS feynman_kind")
