"""review_item

Revision ID: b1c2d3e4f5a6
Revises: a1b2c3d4e5f6
Create Date: 2026-04-27 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'review_item',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('concept_id', sa.Uuid(), nullable=False),
        sa.Column('embed_dim', sa.Integer(), nullable=False),
        sa.Column('ease', sa.Float(), nullable=False),
        sa.Column('interval_days', sa.Integer(), nullable=False),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_session_id', sa.Uuid(), nullable=True),
        sa.Column('last_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['last_session_id'], ['feynman_session.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'uq_review_item_user_concept_dim',
        'review_item',
        ['user_id', 'concept_id', 'embed_dim'],
        unique=True,
    )
    op.create_index(
        'ix_review_item_user_due',
        'review_item',
        ['user_id', 'due_at'],
        unique=False,
    )
    # Per-column indexes generated by SQLAlchemy for FK and concept_id
    op.create_index(
        op.f('ix_review_item_user_id'),
        'review_item',
        ['user_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_review_item_concept_id'),
        'review_item',
        ['concept_id'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_review_item_concept_id'), table_name='review_item')
    op.drop_index(op.f('ix_review_item_user_id'), table_name='review_item')
    op.drop_index('ix_review_item_user_due', table_name='review_item')
    op.drop_index('uq_review_item_user_concept_dim', table_name='review_item')
    op.drop_table('review_item')
