"""papers chunks concepts

Revision ID: e4ad1e7b8012
Revises: c60d4afd5b47
Create Date: 2026-04-24 13:26:06.212633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e4ad1e7b8012'
down_revision: Union[str, Sequence[str], None] = 'c60d4afd5b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension exists before any vector columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Create enum types idempotently before table creation
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE paper_status AS ENUM ('uploaded', 'parsed', 'failed');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE concept_stage AS ENUM ('new', 'learning', 'fluent', 'teach');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE edge_status AS ENUM ('proposed', 'accepted', 'rejected');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_1024',
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_paper_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('stage', PGEnum('new', 'learning', 'fluent', 'teach', name='concept_stage', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_1024_user_id'), 'concept_1024', ['user_id'], unique=False)
    op.create_table('concept_1536',
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_paper_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('stage', PGEnum('new', 'learning', 'fluent', 'teach', name='concept_stage', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_1536_user_id'), 'concept_1536', ['user_id'], unique=False)
    op.create_table('concept_768',
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_paper_ids', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('stage', PGEnum('new', 'learning', 'fluent', 'teach', name='concept_stage', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_768_user_id'), 'concept_768', ['user_id'], unique=False)
    op.create_table('concept_edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('src_id', sa.Uuid(), nullable=False),
    sa.Column('dst_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('status', PGEnum('proposed', 'accepted', 'rejected', name='edge_status', create_type=False), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_edge_dst_id'), 'concept_edge', ['dst_id'], unique=False)
    op.create_index(op.f('ix_concept_edge_src_id'), 'concept_edge', ['src_id'], unique=False)
    op.create_index(op.f('ix_concept_edge_user_id'), 'concept_edge', ['user_id'], unique=False)
    op.create_table('paper',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('status', PGEnum('uploaded', 'parsed', 'failed', name='paper_status', create_type=False), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_text_hash'), 'paper', ['text_hash'], unique=False)
    op.create_index(op.f('ix_paper_user_id'), 'paper', ['user_id'], unique=False)
    op.create_table('paper_chunk_1024',
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_chunk_1024_paper_id'), 'paper_chunk_1024', ['paper_id'], unique=False)
    op.create_table('paper_chunk_1536',
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_chunk_1536_paper_id'), 'paper_chunk_1536', ['paper_id'], unique=False)
    op.create_table('paper_chunk_768',
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_chunk_768_paper_id'), 'paper_chunk_768', ['paper_id'], unique=False)
    # ### end Alembic commands ###

    # ivfflat cosine indexes on all embedding columns
    for table in (
        "paper_chunk_768", "paper_chunk_1024", "paper_chunk_1536",
        "concept_768", "concept_1024", "concept_1536",
    ):
        op.execute(
            f"CREATE INDEX ix_{table}_embedding_cos ON {table} "
            f"USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop ivfflat indexes before dropping tables
    for table in (
        "paper_chunk_768", "paper_chunk_1024", "paper_chunk_1536",
        "concept_768", "concept_1024", "concept_1536",
    ):
        op.execute(f"DROP INDEX IF EXISTS ix_{table}_embedding_cos")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_chunk_768_paper_id'), table_name='paper_chunk_768')
    op.drop_table('paper_chunk_768')
    op.drop_index(op.f('ix_paper_chunk_1536_paper_id'), table_name='paper_chunk_1536')
    op.drop_table('paper_chunk_1536')
    op.drop_index(op.f('ix_paper_chunk_1024_paper_id'), table_name='paper_chunk_1024')
    op.drop_table('paper_chunk_1024')
    op.drop_index(op.f('ix_paper_user_id'), table_name='paper')
    op.drop_index(op.f('ix_paper_text_hash'), table_name='paper')
    op.drop_table('paper')
    op.drop_index(op.f('ix_concept_edge_user_id'), table_name='concept_edge')
    op.drop_index(op.f('ix_concept_edge_src_id'), table_name='concept_edge')
    op.drop_index(op.f('ix_concept_edge_dst_id'), table_name='concept_edge')
    op.drop_table('concept_edge')
    op.drop_index(op.f('ix_concept_768_user_id'), table_name='concept_768')
    op.drop_table('concept_768')
    op.drop_index(op.f('ix_concept_1536_user_id'), table_name='concept_1536')
    op.drop_table('concept_1536')
    op.drop_index(op.f('ix_concept_1024_user_id'), table_name='concept_1024')
    op.drop_table('concept_1024')
    # ### end Alembic commands ###

    # Drop enum types that were created in upgrade
    op.execute("DROP TYPE IF EXISTS paper_status")
    op.execute("DROP TYPE IF EXISTS concept_stage")
    op.execute("DROP TYPE IF EXISTS edge_status")

    op.execute("DROP EXTENSION IF EXISTS vector")
